#!./venv/bin/python

id = 'id'
users = 'Users'
notification = 'Notification'
notifications = 'Notifications'
notificationCore = 'notificationCore'
notificationCores = 'notificationCores'
rules = 'Rules'
user_id = 'user_id'
notification_id = 'notification_id'
rule_id = 'rule_id'
username = 'username'
email = 'email'
phone = 'phone'
rule = 'rule'
last_sent = 'last_sent'
app_db = 'app.db'
fullpvlist_db = 'fullpvlist.db'
pv = 'pv'
